config/routes.rb
Rails.application.routes.draw do
  get 'rules/index'

  resources :calenders
  resources :affiliates
  resources :dividends
  resources :message_reads
  resources :messages
  resources :system_infos
  resources :topics
  root :to => 'welcome#index'
  resources :stock_monitors
  resources :stock_infos
  resources :banks
  resources :stock_holds
  devise_for :users
  get 'welcome/index'
  get 'stock_holds/list/:p_list' , to: 'stock_holds#index'
  get '/stock_holds/:id/edit/:p_list' , to: 'stock_holds#edit'
  get '/stock_holds/new/:p_list' , to: 'stock_holds#new'
  get '/stock_holds/:id/:p_list' , to: 'stock_holds#show'
  patch '/stock_holds/:id/:p_list', to: 'stock_holds#update'

  get 'stock_infos/search/:p_list' , to: 'stock_infos#search'

  post 'stock_infos/search2' , to: 'stock_infos#search2'
  #post 'stock_infos/index' , to: 'stock_infos#index'

  get  'stock_infos/search2/:p_list' , to: 'stock_infos#search2'
  get 'stock_infos/hold/:p_list' , to: 'stock_infos#hold'
  get 'stock_monitors/new/:p_list' , to: 'stock_monitors#new'
  get 'banks/hold/:p_list' , to: 'banks#hold'

  #保有銘柄一覧から配当金登録
  get '/dividends/new/jpn_stock/:p_bank_id/:p_stock_type/:p_stock_code' , to: 'dividends#new'
  get '/dividends/new/jpn_other_stock/:p_bank_id/:p_stock_type/:p_stock_name' , to: 'dividends#new'
  get '/dividends/new/stock_code/:p_stock_code' , to: 'dividends#new'


  #お問い合わせ
  get 'inquiry' => 'inquiry#index'              # 入力画面
  post 'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post 'inquiry/thanks' => 'inquiry#thanks'     # 送信完了画面

  #ルーティングエラーは、アプリケーションコントローラーのエラー処理を実行
  get  '*unmatched_route', to: 'application#raise_not_found!', format: false

  #get '/stock_infos', to: 'stock_infos#index'
  #get '/stock_infos/:id', to: 'stock_infos#show'
end

app/models/message.rb
#お知らせ一覧
class Message < ApplicationRecord
  #結合
  belongs_to :user

  #必須チェック
  validates :send_date, presence: true
  validates :subject, presence: true
  validates :body, presence: true

  #日付
  validates_datetime :send_date

end

app/controllers/messages_controller.rb
#お知らせ
class MessagesController < ApplicationController
  include CommonModule
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :sign_in_required

  def index
    #既読かつ削除は表示対象から除外
    @messages = Message.joins("LEFT JOIN message_reads on messages.id=message_reads.message_id").where("messages.user_id=? or messages.user_id is null",current_user.id.to_s)
                    .select("messages.*,message_reads.read_flg,message_reads.delete_flg")
                    .order("messages.created_at desc")
                    .where.not(id: MessageRead.where("message_reads.user_id=? and delete_flg=?",current_user.id,true).select("message_id"))

    #ページング
    @messages = @messages.page(params[:page]).per(5)
  end

  def show
    #お知らせを既読に設定
    #お知らせのメールアドレス指定がある場合 と メールアドレス指定がない場合 の２種類のメッセージを取得
    if MessageRead.find_by(user_id: current_user.id, message_id: @message.id).nil?
      message_read = MessageRead.new
      message_read.message_id = @message.id
      message_read.user_id =current_user.id
      message_read.read_flg = true
      message_read.delete_flg = false
      if message_read.save
        flash.now[:notice] = "お知らせを既読にしました。"
      else
        flash.now[:notice] = "お知らせの既読に失敗しました。インターネット接続またはWebサービスが一時的に問題が出ています。"
      end
    end
  end

  def new
    if check_role(current_user)
      @message = Message.new
    end
  end

  def edit
    check_role(current_user)
  end

  def create
    if check_role(current_user)
      @message = Message.new(message_params)
      @message.user_id =current_user.id
      respond_to do |format|
        if @message.save
          format.html { redirect_to @message, notice: 'お知らせを登録しました。' }
        else
          format.html { render :new }
        end
      end
    end
  end

  def update
    if check_role(current_user)
      respond_to do |format|
        if @message.update(message_params)
          format.html { redirect_to @message, notice: 'お知らせを更新しました。' }
        else
          format.html { render :edit }
        end
      end
    end
  end

  def destroy
    message_read = MessageRead.find_by(user_id: current_user.id, message_id: @message.id)
    if !message_read.nil?
      message_read.delete_flg = true
      if message_read.save
        redirect_to messages_url, notice: '対象のお知らせを削除しました。'
      else
        redirect_to messages_url, notice: '対象のお知らせの削除に失敗しました。インターネット接続またはWebサービスが一時的に問題が出ています。'
      end
    end
  end

  private
    def set_message
      @message = Message.where("user_id = "  +current_user.id.to_s + " or user_id is null or user_id =''").find_by_id(params[:id])
    end

    def message_params
      params.require(:message).permit(:user_id, :send_date, :subject, :body)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<% if @message.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= @message.errors.count %>件のエラーがあります。</h2>

      <ul>
        <% @message.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<%= simple_form_for @message, :html => { :class => 'form-horizontal' 'text-left'} do |f| %>
    <div class="input-group date-range-picker-width" >
      <%= f.input :send_date  , as: :date_picker , :input_html => {:maxlength =>10,:style=> 'width: 130px'}%>
    </div>
    <%= f.input :subject ,:input_html => {:maxlength =>50,:style=> 'width: 430px'}%>
    <%= f.input :body ,:input_html => {:maxlength =>500,:style=> 'width: 430px;min-height: 220px;'}%>
  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                messages_path, :class => 'btn btn-default' %>
<% end %>
<br>
<br>
<br>

app/views/messages/edit.html.erb
<%- model_class = Message -%>

  <h3>お知らせ</h3>

<%= render :partial => 'form' %>

app/views/messages/index.html.erb
<%- model_class = Message -%>

  <h3>お知らせ一覧</h3>

<% if @messages.records.count >0 then%>
    <table class="table table-striped table-bordered table-condensed" style="table-layout:fixed;width:590px;">
      <thead>
      <tr>
        <th class="text-center" style="width:130px;"><%= model_class.human_attribute_name(:created_at) %></th>
        <th class="text-center" style="width:140px;">宛先</th>
        <th class="text-center" style="width:220px;"><%= model_class.human_attribute_name(:subject) %></th>
        <th class="text-center" style="width:80px;"></th>
      </tr>
      </thead>
      <tbody>
      <% @messages.each do |message| %>
          <tr>
            <td>
              <%=l message.created_at %>
              <br>
              <% if message.read_flg%>
              【既読】
              <% else %>
              【未読】
              <% end %>
            </td>
            <td>
              <% if message.user_id.to_s =="" %>
                  利用者全員
              <% else %>
                  個別連絡
              <% end %>

            </td>
            <td>
              <%= link_to message.subject, message_path(message)  %>
            </td>
            <td>
              <%= link_to t('.show', :default => t("helpers.links.show")),
                          message_path(message), :class => 'btn btn-default btn-block' %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <%= paginate @messages %><br>
<% else%>
    <p class="text-info">
      お知らせはありません<br><br>
    </p>
<% end %>


<!--
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_message_path,
            :class => 'btn btn-default' %>-->
<br>
<br>
<br>

app/views/messages/new.html.erb
<%- model_class = Message -%>

  <h3>お知らせ</h3>

<%= render :partial => 'form' %>

app/views/messages/show.html.erb
<%- model_class = Message -%>

  <h3>お知らせ</h3>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:send_date) %>:</strong></dt>
  <dd><%= @message.send_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:subject) %>:</strong></dt>
  <dd><%= @message.subject %></dd>
  <dt><strong><%= model_class.human_attribute_name(:body) %>:</strong></dt>
  <dd><%= raw(@message.body) %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              messages_path, :class => 'btn btn-default'  %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              message_path(@message),
              :method => 'delete',
            :data => { :confirm => "削除してよろしいですか？" ,cancel: "キャンセル",commit: "削除"}, title: "削除確認",
            :class => 'btn btn-default' %>
<br>
<br>
<br>