config/routes.rb
Rails.application.routes.draw do
  get 'rules/index'

  resources :calenders
  resources :affiliates
  resources :dividends
  resources :message_reads
  resources :messages
  resources :system_infos
  resources :topics
  root :to => 'welcome#index'
  resources :stock_monitors
  resources :stock_infos
  resources :banks
  resources :stock_holds
  devise_for :users
  get 'welcome/index'
  get 'stock_holds/list/:p_list' , to: 'stock_holds#index'
  get '/stock_holds/:id/edit/:p_list' , to: 'stock_holds#edit'
  get '/stock_holds/new/:p_list' , to: 'stock_holds#new'
  get '/stock_holds/:id/:p_list' , to: 'stock_holds#show'
  patch '/stock_holds/:id/:p_list', to: 'stock_holds#update'

  get 'stock_infos/search/:p_list' , to: 'stock_infos#search'

  post 'stock_infos/search2' , to: 'stock_infos#search2'
  #post 'stock_infos/index' , to: 'stock_infos#index'

  get  'stock_infos/search2/:p_list' , to: 'stock_infos#search2'
  get 'stock_infos/hold/:p_list' , to: 'stock_infos#hold'
  get 'stock_monitors/new/:p_list' , to: 'stock_monitors#new'
  get 'banks/hold/:p_list' , to: 'banks#hold'

  #保有銘柄一覧から配当金登録
  get '/dividends/new/jpn_stock/:p_bank_id/:p_stock_type/:p_stock_code' , to: 'dividends#new'
  get '/dividends/new/jpn_other_stock/:p_bank_id/:p_stock_type/:p_stock_name' , to: 'dividends#new'
  get '/dividends/new/stock_code/:p_stock_code' , to: 'dividends#new'


  #お問い合わせ
  get 'inquiry' => 'inquiry#index'              # 入力画面
  post 'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post 'inquiry/thanks' => 'inquiry#thanks'     # 送信完了画面

  #ルーティングエラーは、アプリケーションコントローラーのエラー処理を実行
  get  '*unmatched_route', to: 'application#raise_not_found!', format: false

  #get '/stock_infos', to: 'stock_infos#index'
  #get '/stock_infos/:id', to: 'stock_infos#show'
end

app/models/calender.rb
class Calender < ApplicationRecord
end

app/controllers/calenders_controller.rb
class CalendersController < ApplicationController
  before_action :set_calender, only: [:show, :edit, :update, :destroy]

  # GET /calenders
  # GET /calenders.json
  def index
    @calenders = Calender.all
  end

  # GET /calenders/1
  # GET /calenders/1.json
  def show
  end

  # GET /calenders/new
  def new
    @calender = Calender.new
  end

  # GET /calenders/1/edit
  def edit
  end

  # POST /calenders
  # POST /calenders.json
  def create
    @calender = Calender.new(calender_params)

    respond_to do |format|
      if @calender.save
        format.html { redirect_to @calender, notice: 'Calender was successfully created.' }
        format.json { render :show, status: :created, location: @calender }
      else
        format.html { render :new }
        format.json { render json: @calender.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calenders/1
  # PATCH/PUT /calenders/1.json
  def update
    respond_to do |format|
      if @calender.update(calender_params)
        format.html { redirect_to @calender, notice: 'Calender was successfully updated.' }
        format.json { render :show, status: :ok, location: @calender }
      else
        format.html { render :edit }
        format.json { render json: @calender.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calenders/1
  # DELETE /calenders/1.json
  def destroy
    @calender.destroy
    respond_to do |format|
      format.html { redirect_to calenders_url, notice: 'Calender was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calender
      @calender = Calender.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calender_params
      params.require(:calender).permit(:opt, :holliday, :description)
    end
end

app/helpers/calenders_helper.rb
module CalendersHelper
end

app/views/calenders/_form.html.erb
<%= simple_form_for @calender, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :opt %>
  <%= f.input :holliday %>
  <%= f.input :description %>
  <%= f.button :submit, :class => 'btn-default' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                calenders_path, :class => 'btn btn-default' %>
<% end %>

app/views/calenders/edit.html.erb
<%- model_class = Calender -%>
  <h3><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h3>
<%= render :partial => 'form' %>

app/views/calenders/index.html.erb
<%- model_class = Calender -%>

  <h3><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h3>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:opt) %></th>
      <th><%= model_class.human_attribute_name(:holliday) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @calenders.each do |calender| %>
      <tr>
        <td><%= link_to calender.id, calender_path(calender) %></td>
        <td><%= calender.opt %></td>
        <td><%= calender.holliday %></td>
        <td><%= calender.description %></td>
        <td><%=l calender.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_calender_path(calender), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      calender_path(calender),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-default' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_calender_path,
            :class => 'btn btn-default' %>

app/views/calenders/new.html.erb
<%- model_class = Calender -%>
  <h3><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h3>
<%= render :partial => 'form' %>

app/views/calenders/show.html.erb
<%- model_class = Calender -%>
  <h3><%=t '.title', :default => model_class.model_name.human.titleize %></h3>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:opt) %>:</strong></dt>
  <dd><%= @calender.opt %></dd>
  <dt><strong><%= model_class.human_attribute_name(:holliday) %>:</strong></dt>
  <dd><%= @calender.holliday %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @calender.description %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              calenders_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_calender_path(@calender), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              calender_path(@calender),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-default' %>