config/routes.rb
Rails.application.routes.draw do
  get 'rules/index'

  resources :calenders
  resources :affiliates
  resources :dividends
  resources :message_reads
  resources :messages
  resources :system_infos
  resources :topics
  root :to => 'welcome#index'
  resources :stock_monitors
  resources :stock_infos
  resources :banks
  resources :stock_holds
  devise_for :users
  get 'welcome/index'
  get 'stock_holds/list/:p_list' , to: 'stock_holds#index'
  get '/stock_holds/:id/edit/:p_list' , to: 'stock_holds#edit'
  get '/stock_holds/new/:p_list' , to: 'stock_holds#new'
  get '/stock_holds/:id/:p_list' , to: 'stock_holds#show'
  patch '/stock_holds/:id/:p_list', to: 'stock_holds#update'

  get 'stock_infos/search/:p_list' , to: 'stock_infos#search'

  post 'stock_infos/search2' , to: 'stock_infos#search2'
  #post 'stock_infos/index' , to: 'stock_infos#index'

  get  'stock_infos/search2/:p_list' , to: 'stock_infos#search2'
  get 'stock_infos/hold/:p_list' , to: 'stock_infos#hold'
  get 'stock_monitors/new/:p_list' , to: 'stock_monitors#new'
  get 'banks/hold/:p_list' , to: 'banks#hold'

  #保有銘柄一覧から配当金登録
  get '/dividends/new/jpn_stock/:p_bank_id/:p_stock_type/:p_stock_code' , to: 'dividends#new'
  get '/dividends/new/jpn_other_stock/:p_bank_id/:p_stock_type/:p_stock_name' , to: 'dividends#new'
  get '/dividends/new/stock_code/:p_stock_code' , to: 'dividends#new'


  #お問い合わせ
  get 'inquiry' => 'inquiry#index'              # 入力画面
  post 'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post 'inquiry/thanks' => 'inquiry#thanks'     # 送信完了画面

  #ルーティングエラーは、アプリケーションコントローラーのエラー処理を実行
  get  '*unmatched_route', to: 'application#raise_not_found!', format: false

  #get '/stock_infos', to: 'stock_infos#index'
  #get '/stock_infos/:id', to: 'stock_infos#show'
end

app/models/system_info.rb
class SystemInfo < ApplicationRecord
  #必須
  validates :send_date, presence: true
  validates :subject, presence: true
  validates :body, presence: true

  #日付チェック
  validates_datetime :send_date

end

app/controllers/system_infos_controller.rb
class SystemInfosController < ApplicationController
  include CommonModule
  before_action :set_system_info, only: [:show, :edit, :update, :destroy]
  before_action :sign_in_required

  def index
    @system_infos = SystemInfo.all
    #ページング
    @system_infos = @system_infos.page(params[:page]).per(5)
  end

  def show
  end

  def new
    if check_role(current_user)
      @system_info = SystemInfo.new
    end
  end

  def edit
    check_role(current_user)
  end

  def create
    if check_role(current_user)
      @system_info = SystemInfo.new(system_info_params)

      respond_to do |format|
        if @system_info.save
          format.html { redirect_to @system_info, notice: 'メンテナンス情報を登録しました。' }
        else
          format.html { render :new }
        end
      end
    end
  end

  def update
    if check_role(current_user)
      respond_to do |format|
        if @system_info.update(system_info_params)
          format.html { redirect_to @system_info, notice: 'メンテナンス情報を更新しました。' }
        else
          format.html { render :edit }
        end
      end
    end
  end

  def destroy
    if check_role(current_user)
      @system_info.destroy
      respond_to do |format|
        format.html { redirect_to system_infos_url, notice: '対象のメンテナンス情報を削除しました。' }
      end
    end
  end

  private
    def set_system_info
      @system_info = SystemInfo.find(params[:id])
    end

    def system_info_params
      params.require(:system_info).permit(:send_date, :subject, :body)
    end
end

app/helpers/system_infos_helper.rb
module SystemInfosHelper
end

app/views/system_infos/_form.html.erb
<% if @system_info.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= @system_info.errors.count %>件のエラーがあります。</h2>

      <ul>
        <% @system_info.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<%= simple_form_for @system_info, :html => { :class => 'form-horizontal' 'text-left'} do |f| %>
    <div class="input-group date-range-picker-width" >
      <%= f.input :send_date  , as: :date_picker , :input_html => {:maxlength =>10,:style=> 'width: 130px'}%>
    </div>
  <%= f.input :subject ,:input_html => {:maxlength =>50,:style=> 'width: 430px'}%>
  <%= f.input :body ,:input_html => {:maxlength =>500,:style=> 'width: 430px;min-height: 220px;'}%>
  <%= f.button :submit, :class => 'btn-default' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                system_infos_path, :class => 'btn btn-default' %>
<% end %>
<br>
<br>
<br>

app/views/system_infos/edit.html.erb
<%- model_class = SystemInfo -%>

  <h3>メンテナンス情報</h3>

<%= render :partial => 'form' %>

app/views/system_infos/index.html.erb
<%- model_class = SystemInfo -%>

  <h3>メンテナンス情報</h3>

<% if @system_infos.records.count >0 then%>
    <table class="table table-striped table-bordered table-condensed" style="table-layout:fixed;width:590px;">
      <thead>
      <tr>
        <th class="text-center" style="width:140px;"><%= model_class.human_attribute_name(:created_at) %></th>
        <th class="text-center" style="width:300px;"><%= model_class.human_attribute_name(:subject) %></th>
        <th class="text-center" style="width:80px;"></th>
      </tr>
      </thead>
      <tbody>
      <% @system_infos.each do |system_info| %>
          <tr>
            <td><%=l system_info.created_at %></td>
            <td>
              <%= link_to system_info.subject, system_info_path(system_info)  %>
            </td>
            <td class="text-center">
              <%= link_to t('.show', :default => t("helpers.links.show")),
                          system_info_path(system_info), :class => 'btn btn-default btn-block' %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <%= paginate @system_infos %><br>
<% else%>
    <span class="text-info " >
      <dl id="info_list">
        <dt><i class="glyphicon glyphicon-info-sign"></i></dt><dd>メンテナンス情報はありません</dd>
      </dl>
    </span>
<% end %>
<br>
<br>
<br>

app/views/system_infos/new.html.erb
<%- model_class = SystemInfo -%>

  <h3>メンテナンス情報</h3>

<%= render :partial => 'form' %>

app/views/system_infos/show.html.erb
<%- model_class = SystemInfo -%>

  <h3>メンテナンス情報</h3>


<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:send_date) %>:</strong></dt>
  <dd><%= @system_info.send_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:subject) %>:</strong></dt>
  <dd><%= @system_info.subject %></dd>
  <dt><strong><%= model_class.human_attribute_name(:body) %>:</strong></dt>
  <dd><%= @system_info.body %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              system_infos_path, :class => 'btn btn-default'  %>
<br>
<br>
<br>