config/routes.rb
Rails.application.routes.draw do
  get 'rules/index'

  resources :calenders
  resources :affiliates
  resources :dividends
  resources :message_reads
  resources :messages
  resources :system_infos
  resources :topics
  root :to => 'welcome#index'
  resources :stock_monitors
  resources :stock_infos
  resources :banks
  resources :stock_holds
  devise_for :users
  get 'welcome/index'
  get 'stock_holds/list/:p_list' , to: 'stock_holds#index'
  get '/stock_holds/:id/edit/:p_list' , to: 'stock_holds#edit'
  get '/stock_holds/new/:p_list' , to: 'stock_holds#new'
  get '/stock_holds/:id/:p_list' , to: 'stock_holds#show'
  patch '/stock_holds/:id/:p_list', to: 'stock_holds#update'

  get 'stock_infos/search/:p_list' , to: 'stock_infos#search'

  post 'stock_infos/search2' , to: 'stock_infos#search2'
  #post 'stock_infos/index' , to: 'stock_infos#index'

  get  'stock_infos/search2/:p_list' , to: 'stock_infos#search2'
  get 'stock_infos/hold/:p_list' , to: 'stock_infos#hold'
  get 'stock_monitors/new/:p_list' , to: 'stock_monitors#new'
  get 'banks/hold/:p_list' , to: 'banks#hold'

  #保有銘柄一覧から配当金登録
  get '/dividends/new/jpn_stock/:p_bank_id/:p_stock_type/:p_stock_code' , to: 'dividends#new'
  get '/dividends/new/jpn_other_stock/:p_bank_id/:p_stock_type/:p_stock_name' , to: 'dividends#new'
  get '/dividends/new/stock_code/:p_stock_code' , to: 'dividends#new'


  #お問い合わせ
  get 'inquiry' => 'inquiry#index'              # 入力画面
  post 'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post 'inquiry/thanks' => 'inquiry#thanks'     # 送信完了画面

  #ルーティングエラーは、アプリケーションコントローラーのエラー処理を実行
  get  '*unmatched_route', to: 'application#raise_not_found!', format: false

  #get '/stock_infos', to: 'stock_infos#index'
  #get '/stock_infos/:id', to: 'stock_infos#show'
end

app/models/inquiry.rb
#メール
class Inquiry
  include ActiveModel::Model
  attr_accessor :name, :email, :message
  #名前 50文字以内
  #メッセージ 1000文字

  #メールアドレスチェック
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,  format: { with: VALID_EMAIL_REGEX }

  #文字数チェック
  validates :name,      length: { maximum: 50 }
  validates :email,     length: { maximum: 50 }
  validates :message,   length: { maximum: 1000 }

  #必須入力チェック
  validate :error_must_input
  def error_must_input
    if name.blank?
      errors[:base] << "名前は必ず入力して下さい"
    end

    if email.blank?
      errors[:base] << "メールアドレスは必ず入力して下さい"
    end

    if message.blank?
      errors[:base] << "お問い合わせ内容は必ず入力して下さい"
    end
  end
end

app/controllers/inquiry_controller.rb
#お問い合わせ
class InquiryController < ApplicationController
  #入力画面
  def index
    # 入力画面を表示
    @inquiry = Inquiry.new
    render :action => 'index'
  end

  #確認画面
  def confirm
    @inquiry = Inquiry.new(inquiry_params)
    # 入力値のチェック
    if @inquiry.valid?
      # OK。確認画面を表示
      render :action => 'confirm'
    else
      # NG。入力画面を再表示
      render :action => 'index'
    end
  end

  #メール送信、お問い合わせ完了画面
  def thanks
    # メール送信
    @inquiry = Inquiry.new(inquiry_params)
    InquiryMailer.received_email(@inquiry).deliver

    # 完了画面を表示
    render :action => 'thanks'
  end

  # 登録、更新パラメーターの許可制限を設定
  def inquiry_params
    params.require(:inquiry).permit(:name,:email,:message)
  end
end

app/views/inquiry/confirm.html.erb
<h3>お問い合わせ送信確認</h3>

<%= form_for @inquiry, :url => inquiry_thanks_path do |f| %>
    <div class="">
      <table class="table  table-bordered table-condensed" style="table-layout:fixed;width:580px;">
        <tr>
          <th width="150">名前</th>
          <td width="530">
            <%= f.hidden_field :name %>
            <%= @inquiry.name %>
          </td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td>
            <%= f.hidden_field :email %>
            <%= @inquiry.email %>
          </td>
        </tr>
        <tr>
          <th>お問い合わせ内容</th>
          <td>
            <%= f.hidden_field :message %>
            <TEXTAREA  rows="20" style="width: 500px;border-style: none; color:#000000; background-color:#ffffff;resize: none;" disabled="disabled"><%=@inquiry.message %></TEXTAREA>
          </td>
        </tr>
      </table>

    </div>
    <span class="text-info " >
      <dl id="info_list">
        <dt><i class="glyphicon glyphicon-warning-sign"></i></dt><dd>メールアドレスに誤りがない事をご確認ください</dd>
      </dl>
    </span>
    <%= f.submit '送信', :class => 'btn btn-default' %>
    <input type="button" class ='btn btn-default' value="戻る" onClick="history.back()">
<% end %>
<br>
<br>
<br>

app/views/inquiry/index.html.erb
<% if @inquiry.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= @inquiry.errors.count %>件のエラーがあります。</h2>

      <ul>
        <% @inquiry.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<h3>お問い合わせ入力</h3>

<span class="text-info " >
  <dl id="info_list">
    <dt><i class="glyphicon glyphicon-warning-sign"></i></dt><dd>ご意見、ご感想をお寄せください</dd>
    <dt><i class="glyphicon glyphicon-warning-sign"></i></dt><dd>本サービスは管理者の技術力向上のため、開発した無料サービスです</dd>
    <dt><i class="glyphicon glyphicon-warning-sign"></i></dt><dd>個別サポートは、原則、対応しかねる事、御了承ください</dd>
  </dl>
</span>

<%= simple_form_for @inquiry, :url => inquiry_confirm_path, :html => { :class => 'form-horizontal' 'text-left'} do |f| %>
    <%= f.label :name ,"* 名前"%>
    <%= f.input :name,:input_html => {:style=> 'width: 550px', :maxlength =>50}, label: false%>

    <%= f.label :email ,"* メールアドレス"%>
    <%= f.input :email ,:input_html => {:style=> 'width: 550px' , :maxlength =>50}, label: false%>

    <%= f.label :message ,"* お問い合わせ内容（1000文字）"%>
    <%= f.input :message , as: :text,:input_html => {:style=> 'width: 500px ;height: 550px ' ,:rows => 10, :maxlength =>1000}, label: false%>
    <span class="text-info " >
      <dl id="info_list">
        <dt><i class="glyphicon glyphicon-warning-sign"></i></dt><dd>メールアドレスに誤りがない事をご確認ください</dd>
      </dl>
    </span>
    <%= f.button :submit, '確認', :class => 'btn-default' %>
<% end %>
<br><br>

app/views/inquiry/thanks.html.erb
  <h3>お問い合わせ完了</h3>


<br>
  お問い合わせ頂き、ありがとうございました。<br><br>
  お問い合わせ内容を確認させていただき、サービス向上に生かします。<br><br>
  個人開発のサービスのため、原則、サポートは致しかねること、御了承ください。
  <br><br>
  <%= link_to 'TOPに戻る', '/',
              :class => 'btn btn-default'%>